### ISSUE TITLE
Server bad

### ISSUE THREAD

**Issue by Stovedal** [SkruvdragarN/APKappen-backend#2]
Without category filter you get Jever:
http://www.skruvdragarn.duckdns.org:1338/APKappen_v2/products?pageIndex=0&postsPerPage=50&store=2401

With category filter you do **not** get Jever:
http://www.skruvdragarn.duckdns.org:1338/APKappen_v2/products?pageIndex=0&postsPerPage=50&store=2401&category=beer

Whyy, only when you filter by store as well.

(Have tested though browser so it's not in the app this time)

**Comment by SkruvdragarN** [comment]
Weird! I assumed Jever was not in any store's assortment. It should be a "Ordervaror"-assortment product. Looking into it within 1000-2000 years. Thank you!

**Comment by SkruvdragarN** [comment]
I can now announce that the problem should be solved. Once again, thank you!
