### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by swenee** [SkruvdragarN/APKappen-backend#4]
There are links to things that Systembolaget does not sell.
Maybe create a blacklist of products that is skipped during parce.
For now a one time blacklist that is created over a period of days could be fine

**Comment by SkruvdragarN** [comment]
Thank you very much for your issue. I'm looking into it!

**Comment by SkruvdragarN** [comment]
Since we filtered out "out-of-stock" products I assume that we have removed most of the broken links.
